### ISSUE TITLE
No subtitles in Livestream

### ISSUE THREAD

**Issue by imjuzcy** [rols1/Kodi-Addon-ARDundZDF#27]
There is no subtitle in live stream, although I can choose to enable subtitle and choose subtitle stream. For example for Das Erste, there is subtitles in the website's live stream, but not available in Kodi through this add-on.

**Comment by rols1** [comment]
the problem with subtitles of ARD livestreams is something known since the beginning of 2022 and unfortunately not solved yet. The team at https://github.com/xbmc/inputstream.adaptive/ is working on it. See [Subtitles from German live broadcasters are not displayed in Kodi 20 (Nexus) #1109](https://github.com/xbmc/inputstream.adaptive/issues/1109)
ZDF live streams should work in all versions of the addon.
/R
P.S. for thisAddon also the german language can be used
