### ISSUE TITLE
Tagesschau via TagesschauXL only in 480p

### ISSUE THREAD

**Issue by unpeeled** [rols1/Kodi-Addon-ARDundZDF#34]
> OS: LibreElec 11.0.5 on RP4
> Kodi: 20.3
> Addon Version: 4.9.4

When i want to watch Tagesschau via TagesschauXL entry it is only displayed in 480P standard quality. All other videos are automatically in 720p/1080p. Also the Tagesschau it self when i open it via "ARD Mediathek".

Click for Reproduce:
- TagesschauXL
- Tagesschau
- tagesschau 17 Uhr (or 20 Uhr) [doesn't matter which one]

This behavior is there since half a year i would guess.

If you need more debug info from my system, let me know.

**Comment by rols1** [comment]
Module TagesschauXL fetches the video sources from the website (embedded in the html code).
Only low resolutions are available there.
I am trying to use the tagesschau24 stream from the ARDStreamlinks for the Tagesschau.
Feedback will follow...

**Comment by unpeeled** [comment]
Hey @rols1 i have no insights of the code and how the addon is working. So if its easy to implement, i'll be glad if it's working. If not it's a little harder to get the HD Video ;)

THX for your work on this Addon. I use it almost every day since a few years ;)

**Comment by rols1** [comment]
it was time for a rebuild. So I integrated following menus into the infrastructure of modul ARDnew:
**tagesschau, tagesschau Gebärdensprache, tagesschau24, tagesschau in 100 SEKUNDEN, tagesthemen und Bericht aus Berlin.**
Maybe other menus follows next time.
Now you can use all available stream-qualities in 3 lists (Streaming, HBBTV, MP4). You see this lists including download-Links with deactivated setting Sofortstart. Otherwise, on setting Sofortstart, the addon takes your settings at Videoformat an Videoqualität. 

Install Einzelupdate TagesschauXL.py like described [in wiki](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/01.-Settings---Allgemein#22-einzelupdate-dateien-und-module). Continue having fun with the addon..

**Comment by unpeeled** [comment]
Just tested it. It works. :smile: Thankyou for your fast Fix.
