### ISSUE TITLE
Missing content type

### ISSUE THREAD

**Issue by linesquarecube** [rols1/Kodi-Addon-ARDundZDF#35]
Hello @rols1, first of all I want to thank you for this great addon! It's in daily use :)

As I'm using a skin ([arctic fuse](https://github.com/jurialmunkey/skin.arctic.fuse)) which provides the content based on the content type, it would be great if you could add the content type to the submenus. Currently, as far as I understood in https://github.com/jurialmunkey/skin.arctic.fuse/issues/462, the content type provided in my example is "none".

Thanks :smiley:

**Comment by rols1** [comment]
Hello linesquarecube.
yes, jurialmunkey is right: the content type is not set in this addon. The reason lies in the history of the addon. It was migrated from the Plex plugin ARDMediathek2016 while largely following the Plex framework. As a result, there were some adaptations to the Kodi interface, but skin-related adjustments were unfortunately not the focus. At the current stage of development, it is too late or too time-consuming for this. I have put some effort into at least being able to select the content type as a setting in the addon. However, this works globally and does not take care of the current video type (movies, episodes).
If you don't know this [setting](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/08.-Settings-Module#16-setze-inhaltstyp-tv-shows-movies-videos-ua) yet, please try it out. It helped some users in the kodinerds forum and maybe it will help you too.

**Comment by C-O-D** [comment]
Could you at least set the content type to 'none' for the menus so that the setting in the options only applies to the content or would that be also too complex? With the Arctic Fuse skin, this would mean that I could have the menus in a square design and the content in landscape...

Best regards

**Comment by rols1** [comment]
this could work and would probably only affect 2 functions in the util module. I'll take a closer look at this later today.
BTW:  the setting ["gesamtes Addon: Verzicht auf Homebuttons"](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/08.-Settings-Module#4-gesamtes-addon-verzicht-auf-homebuttons) makes it possible to disable home buttons.

**Comment by linesquarecube** [comment]
Thank you very much for your answers! Also for the hint regarding the Homebuttons. With setting the overall type to episodes, the addon integrates much better now. As I create widgets for the submenus I need, I can live with that solution. Maybe @C-O-D has a point when it comes to the selection of the view type for menus, as this would differentiate them more from video content in a visual way.

**Comment by rols1** [comment]
Glad to hear it, linesquarecube.

**set content type to 'none' for the menus:**
Adding the missing functions would affect every addDir call in every module. I'm sorry, but I don't have the time to do that. Unfortunately, I was too optimistic here. With menus, I was only thinking of the main menus, not the submenus. The directories are created centrally in the addon (addDir in the util module), but individually for each directory entry. There is no final evaluation at the end of a listing. For this purpose, the addon lacks a higher level instance that sets the content type for the entire directory listing depending on the content. For example, the type "episodes" if the entire list contains episodes. Or "files" or no type for "none" if the list contains submenus with following pages.
An alternative could be to create landscape versions of the addon icons and make them available via settings. With 194 icons, however, this would also be a lot of work.
So, until we find another solution, I can only offer the use of the setting ["Set content type: TV shows, movies, videos, etc."](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/08.-Settings-Module#16-setze-inhaltstyp-tv-shows-movies-videos-ua) .

**Comment by C-O-D** [comment]
Okay, then that can't be changed for now - in any case, thank you for checking and for your efforts...
