### ISSUE TITLE
Audio description in both streams

### ISSUE THREAD

**Issue by rm369** [rols1/Kodi-Addon-ARDundZDF#37]
kodi 21.0, Addon 5.0.3
Playing https://www.ardmediathek.de/video/Y3JpZDovL25kci5kZS81NTliYmZjYS0zNjUwLTRlNDMtYmVjYS03NTc1ZGQ0OGM1MTNfZ2FuemVTZW5kdW5n with the fire tv ARD App offers to turn on or off Audio description. This works.
Using your fine kodi plugin (ARD, Startseite, ESC 2024, Finale in voller Länge) I can choose between two unnamed audio streams, but both include the Audio description (e.g. 2h40').
It should play the audio without description by default, at least optionally.

**Comment by rols1** [comment]
the video source determined by the addon for the video format HLS only contains the different resolutions, no alternative streams like subtitles or audio description. 
I am trying to find out where the problem lies.
In the meantime, the HBBTV streams can be used for this show. To do this, please switch Sofortstart AUS in the context menu.
It looks like ARD is delivering this show for HLS with audio description and for HBBTV without audio description.
![Einzelaufloesungen](https://github.com/rols1/Kodi-Addon-ARDundZDF/assets/12525055/756ac77d-28b6-40c9-b783-79a0b4e36f40)

**Comment by rm369** [comment]
Hi Roland, danke für die schnelle Antwort und den guten Tipp!
Bei https://www.ardmediathek.de/video/eurovision-song-contest/der-countdown-aus-malmoe/das-erste/Y3JpZDovL25kci5kZS8zNTExZTg2Zi0xMzIzLTRmM2YtYjc4MS0zZDQ3NzljZDA1ZDlfZ2FuemVTZW5kdW5n ist es genau umgekehrt: Der (FHD) HLS Stream ist ohne, der hbbtv Stream mit Audiodeskription (0'53").
Solltest Du einen Workaround implementieren, bitte auch hiermit testen...

**Comment by rm369** [comment]
Danke, dass Du dranbleibst!
Hast Du nicht einen Kontakt beim entsprechenden Team bei der ARD, den Du auf die falschen Tags hinweisen könntest?

**Comment by rols1** [comment]
[Kodinerds-Forum](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=502022#post502022):

![Bildschirmfoto_2024-05-14_20-23-14](https://github.com/rols1/Kodi-Addon-ARDundZDF/assets/12525055/694c5fce-2c2c-45b9-82b5-366142046f43)

**Comment by rols1** [comment]
inzwischen habe ich die strm-Funktionen an die ARD-Änderungen angepasst. Die Umsetzung ist jetzt offiziell als Einzelupdates verfügbar. Eine Beschreibung findet sich im [Kodinerds-Forum Post #3.592](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=754134#post754134).
Da nun alle von der ARD angebotenen Video-Formate, einschl. AD und Originalton, im Addon verfügbar sind, betrachte ich das Problem als gelöst.

**Comment by rm369** [comment]
Herzlichen Dank auch hier nochmal! <3
