### ISSUE TITLE
Improvement: "multi-part" broadcasts hard to handle

### ISSUE THREAD

**Issue by 2019-05-10** [rols1/Kodi-Addon-ARDundZDF#6]
Some broadcasts like Extra 3, Quer, regional news are listed with both the complete broadcast and its parts.
That makes it rather difficult to watch the complete brodcast, which probably is the more common scenario.

Since even MediathekView is not really able to select the full broadcast, I assume the data just does not allow for that.
MediathekView allows to set a minimum length, so this may be a viable to solution: in Sort add Length as critierion.

Another idea would be to collect all broadcasts with a common title/theme at the same date/time, set the longest as top node and all the shorter ones as leaves of a second node

- Extra 3 vom XX.XX.XXXX (full)
- Extra 3 vom XX.XX.XXXX (parts)
-- Beitrag X
-- Beitrag Y
-- ...

**Comment by rols1** [comment]
sorry, I'm in hospital - try to answer in a few days./rols1-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.03.21, 11:24 schrieb 2019-05-10 <notifications@github.com>:

   
  Some broadcasts like Extra 3, Quer, regional news are listed with both the complete broadcast and its parts. That makes it rather difficult to watch the complete brodcast, which probably is the more common scenario. 
  Since even MediathekView is not really able to select the full broadcast, I assume the data just does not allow for that. MediathekView allows to set a minimum length, so this may be a viable to solution: in Sort add Length as critierion. 
  Another idea would be to collect all broadcasts with a common title/theme at the same date/time, set the longest as top node and all the shorter ones as leaves of a second node 
   
   Extra 3 vom XX.XX.XXXX (full) 
   Extra 3 vom XX.XX.XXXX (parts) -- Beitrag X -- Beitrag Y -- ...

**Comment by rols1** [comment]
> Another idea would be to collect all broadcasts with a common title/theme at the same date/time, set the longest as top node and all the shorter ones as leaves of a second node

yes, would be nice idea - but would require heavy modifications in addon. The normal workflow is 

- read the website
- branch to following pages if necessary
- list the content in the same order  with buttons for single broadcast

Collecting and  storing the data as in MediathekView for later comparisons  is not provided. 
But I try to identify additional labels like "ganze Sendung" on ARD and ZDF pages to use them as "pre" titlels, possibly colored.
/R

**Comment by rols1** [comment]
see Update V3.8.0. Addon contains 2 customizable sample lists. Titles are marked red on hits.
/R
